---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/schools/{school_id}/classes/{class_id}/students":
    parameters:
    - name: school_id
      in: path
      description: school_id
      required: true
      schema:
        type: string
    - name: class_id
      in: path
      description: class_id
      required: true
      schema:
        type: string
    get:
      summary: students school_class
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
